//! Generation and transactional installation of the SuSFS auto-start module.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
#[cfg(unix)]
use std::fs::File;
use std::fs::{self, OpenOptions};
use std::io::Write as IoWrite;
use std::path::{Path, PathBuf};
#[cfg(not(target_os = "android"))]
use std::sync::{Mutex, MutexGuard};

#[cfg(target_os = "android")]
use std::os::fd::AsRawFd;
#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

use crate::susfs_config::{DEFAULT_BUILD_TIME, DEFAULT_UNAME, ModuleConfig};

const MODULE_ID: &str = "susfs_manager";
const MODULES_DIR: &str = "/data/adb/modules";
const MODULE_PATH: &str = "/data/adb/modules/susfs_manager";
const MODULE_STAGE_PATH: &str = "/data/adb/modules/.susfs_manager.stage";
const MODULE_BACKUP_PATH: &str = "/data/adb/modules/.susfs_manager.backup";
const MODULE_LOCK_PATH: &str = "/data/adb/ksu/susfs_module.lock";
const LOG_DIR: &str = "/data/adb/ksu/log";

#[cfg(not(target_os = "android"))]
static MODULE_MUTEX: Mutex<()> = Mutex::new(());

struct ModuleLock {
    #[cfg(target_os = "android")]
    _file: File,
    #[cfg(not(target_os = "android"))]
    _guard: MutexGuard<'static, ()>,
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn script_prelude(log_file_name: &str, stage_name: &str) -> String {
    format!(
        r#"#!/system/bin/sh
LOG_DIR="{LOG_DIR}"
LOG_FILE="$LOG_DIR/{log_file_name}"
KSUD="/data/adb/ksud"

mkdir -p "$LOG_DIR"

log_message() {{
    printf '%s: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG_FILE"
}}

run_susfs() {{
    "$KSUD" susfs "$@" >> "$LOG_FILE" 2>&1
    local status=$?
    if [ "$status" -ne 0 ]; then
        log_message "command failed ($status): susfs $*"
    fi
    return "$status"
}}

wait_for_path() {{
    local path="$1"
    local timeout="$2"
    local elapsed=0
    while [ ! -e "$path" ] && [ "$elapsed" -lt "$timeout" ]; do
        sleep 1
        elapsed=$((elapsed + 1))
    done
    [ -e "$path" ]
}}

if [ ! -x "$KSUD" ]; then
    log_message "ksud is missing or not executable: $KSUD"
    exit 1
fi

log_message "{stage_name} started"
"#,
    )
}

fn finish_script(script: &mut String, stage_name: &str) {
    writeln!(
        script,
        "\nlog_message {}",
        shell_quote(&format!("{stage_name} completed"))
    )
    .ok();
}

fn module_prop() -> String {
    format!(
        "id={MODULE_ID}\n\
         name=MakoSU SuSFS\n\
         version={}\n\
         versionCode={}\n\
         author=MakoSU\n\
         description=Transactional SuSFS auto-start configuration generated by MakoSU.\n\
         updateJson=\n",
        env!("VERSION_NAME"),
        env!("VERSION_CODE")
    )
}

fn path_needs_android_storage(path: &str) -> bool {
    path.starts_with("/sdcard/")
        || path.starts_with("/storage/emulated/")
        || path.starts_with("/data/media/")
}

fn append_hide_bootloader(script: &mut String) {
    script.push_str(
        r#"
RESETPROP_BIN="/data/adb/ksu/bin/resetprop"

wait_for_property() {
    local name="$1"
    local expected="$2"
    local timeout="$3"
    local elapsed=0
    while [ "$(getprop "$name")" != "$expected" ] && [ "$elapsed" -lt "$timeout" ]; do
        sleep 1
        elapsed=$((elapsed + 1))
    done
    [ "$(getprop "$name")" = "$expected" ]
}

set_prop() {
    local name="$1"
    local expected="$2"
    local current
    current=$("$RESETPROP_BIN" "$name" 2>/dev/null)
    [ "$current" = "$expected" ] || "$RESETPROP_BIN" "$name" "$expected"
}

set_prop_if_missing() {
    local name="$1"
    local expected="$2"
    local current
    current=$("$RESETPROP_BIN" "$name" 2>/dev/null)
    [ -n "$current" ] || "$RESETPROP_BIN" "$name" "$expected"
}

replace_prop_fragment() {
    local name="$1"
    local fragment="$2"
    local replacement="$3"
    case "$("$RESETPROP_BIN" "$name" 2>/dev/null)" in
        *"$fragment"*) "$RESETPROP_BIN" "$name" "$replacement" ;;
    esac
}

if [ ! -x "$RESETPROP_BIN" ]; then
    log_message "resetprop is unavailable; bootloader property spoofing skipped"
else
    if ! wait_for_property sys.boot_completed 1 120; then
        log_message "timed out waiting for sys.boot_completed; applying properties anyway"
    fi

    set_prop_if_missing ro.boot.vbmeta.invalidate_on_error yes
    set_prop ro.boot.vbmeta.avb_version 1.2
    set_prop ro.boot.vbmeta.hash_alg sha256
    set_prop_if_missing ro.boot.vbmeta.size 19968
    set_prop ro.boot.vbmeta.device_state locked
    set_prop ro.boot.verifiedbootstate green
    set_prop ro.boot.flash.locked 1
    set_prop ro.boot.veritymode enforcing
    set_prop ro.boot.warranty_bit 0
    set_prop ro.warranty_bit 0
    set_prop ro.debuggable 0
    set_prop ro.force.debuggable 0
    set_prop ro.secure 1
    set_prop ro.adb.secure 1
    set_prop ro.build.type user
    set_prop ro.build.tags release-keys
    set_prop ro.vendor.boot.warranty_bit 0
    set_prop ro.vendor.warranty_bit 0
    set_prop vendor.boot.vbmeta.device_state locked
    set_prop vendor.boot.verifiedbootstate green
    set_prop sys.oem_unlock_allowed 0
    set_prop ro.secureboot.lockstate locked
    set_prop ro.boot.realmebootstate green
    set_prop ro.boot.realme.lockstate 1
    set_prop ro.crypto.state encrypted
    "$RESETPROP_BIN" sys.usb.adb.disabled ' '
    replace_prop_fragment ro.bootmode recovery unknown
    replace_prop_fragment ro.boot.bootmode recovery unknown
    replace_prop_fragment vendor.boot.bootmode recovery unknown
    [ -z "$("$RESETPROP_BIN" ro.kernel.qemu 2>/dev/null)" ] || "$RESETPROP_BIN" ro.kernel.qemu ''
    log_message "bootloader properties applied"
fi
"#,
    );
}

fn append_cleanup_residue(script: &mut String) {
    // Only remove known temporary artifacts. User storage and live cgroups are
    // deliberately excluded from this opt-in cleanup.
    const TEMP_PATHS: &[&str] = &[
        "/data/local/tmp/luckys",
        "/data/local/tmp/HyperCeiler",
        "/data/local/tmp/simpleHook",
        "/data/local/tmp/DisabledAllGoogleServices",
        "/data/local/tmp/cleaner_starter",
        "/data/local/tmp/byyang",
        "/data/local/tmp/mount_mask",
        "/data/local/tmp/mount_mark",
        "/data/local/tmp/scriptTMP",
        "/data/local/tmp/horae_control.log",
        "/data/local/tmp/resetprop",
        "/data/local/tmp/Surfing_update",
        "/data/local/tmp/yshell",
        "/data/local/tmp/encore_logo.png",
        "/data/local/tmp/mount_namespace",
    ];

    script.push_str("\nlog_message 'temporary residue cleanup started'\n");
    for path in TEMP_PATHS {
        writeln!(
            script,
            "if [ -e {quoted} ]; then rm -rf {quoted} && log_message {message}; fi",
            quoted = shell_quote(path),
            message = shell_quote(&format!("removed temporary residue: {path}"))
        )
        .ok();
    }
    script.push_str("log_message 'temporary residue cleanup completed'\n");
}

fn append_set_uname(script: &mut String, uname: &str, build_time: &str) {
    writeln!(
        script,
        "run_susfs set-uname {} {}",
        shell_quote(uname),
        shell_quote(build_time)
    )
    .ok();
}

fn append_sus_paths(script: &mut String, paths: &[String]) {
    for path in paths {
        writeln!(script, "run_susfs add-sus-path {}", shell_quote(path)).ok();
    }
}

fn append_loop_paths(script: &mut String, paths: &[String]) {
    for path in paths {
        writeln!(script, "run_susfs add-sus-path-loop {}", shell_quote(path)).ok();
    }
}

fn append_sus_maps(script: &mut String, maps: &[String]) {
    for map in maps {
        writeln!(script, "run_susfs add-sus-map {}", shell_quote(map)).ok();
    }
}

fn append_kstat_config(script: &mut String, config: &str) {
    let parts: Vec<_> = config.split('|').collect();
    if parts.len() != 13 {
        writeln!(
            script,
            "log_message {}",
            shell_quote("ignored malformed static kstat configuration")
        )
        .ok();
        return;
    }

    script.push_str("run_susfs add-sus-kstat-statically");
    for part in &parts {
        write!(script, " {}", shell_quote(part)).ok();
    }
    script.push('\n');
    writeln!(
        script,
        "run_susfs update-sus-kstat {}",
        shell_quote(parts[0])
    )
    .ok();
}

fn generate_service_script(config: &ModuleConfig) -> String {
    let mut script = script_prelude("susfs_service.log", "service stage");

    if !config.sus_paths.is_empty() {
        if config
            .sus_paths
            .iter()
            .any(|path| path_needs_android_storage(path))
        {
            script.push_str(
                "if ! wait_for_path /sdcard/Android 90; then\n\
                     \tlog_message 'timed out waiting for Android storage; paths will be retried at boot-completed'\n\
                 fi\n",
            );
        }
        append_sus_paths(&mut script, &config.sus_paths);
    }

    if !config.execute_in_post_fs_data
        && (config.uname_value != DEFAULT_UNAME || config.build_time_value != DEFAULT_BUILD_TIME)
    {
        append_set_uname(&mut script, &config.uname_value, &config.build_time_value);
    }

    for path in &config.add_kstat_paths {
        writeln!(script, "run_susfs add-sus-kstat {}", shell_quote(path)).ok();
    }
    for kstat in &config.kstat_configs {
        append_kstat_config(&mut script, kstat);
    }

    writeln!(
        script,
        "run_susfs enable-log {}",
        u8::from(config.enable_log)
    )
    .ok();

    if config.enable_hide_bl {
        append_hide_bootloader(&mut script);
    }
    if config.enable_cleanup_residue {
        append_cleanup_residue(&mut script);
    }

    finish_script(&mut script, "service stage");
    script
}

fn generate_post_fs_data_script(config: &ModuleConfig) -> String {
    let mut script = script_prelude("susfs_post_fs_data.log", "post-fs-data stage");

    if config.execute_in_post_fs_data
        && (config.uname_value != DEFAULT_UNAME || config.build_time_value != DEFAULT_BUILD_TIME)
    {
        append_set_uname(&mut script, &config.uname_value, &config.build_time_value);
    }
    writeln!(
        script,
        "run_susfs enable-avc-log-spoofing {}",
        u8::from(config.enable_avc_log_spoofing)
    )
    .ok();

    finish_script(&mut script, "post-fs-data stage");
    script
}

fn generate_post_mount_script() -> String {
    let mut script = script_prelude("susfs_post_mount.log", "post-mount stage");
    finish_script(&mut script, "post-mount stage");
    script
}

fn generate_boot_completed_script(config: &ModuleConfig) -> String {
    let mut script = script_prelude("susfs_boot_completed.log", "boot-completed stage");

    writeln!(
        script,
        "run_susfs hide-sus-mnts-for-non-su-procs {}",
        u8::from(config.hide_sus_mounts_for_all_procs)
    )
    .ok();
    append_sus_paths(&mut script, &config.sus_paths);
    append_loop_paths(&mut script, &config.sus_loop_paths);
    append_sus_maps(&mut script, &config.sus_maps);

    finish_script(&mut script, "boot-completed stage");
    script
}

fn acquire_module_lock() -> Result<ModuleLock> {
    #[cfg(target_os = "android")]
    {
        if let Some(parent) = Path::new(MODULE_LOCK_PATH).parent() {
            fs::create_dir_all(parent).context("Failed to create SuSFS lock directory")?;
        }
        let file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .mode(0o600)
            .open(MODULE_LOCK_PATH)
            .context("Failed to open SuSFS module lock")?;

        loop {
            if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX) } == 0 {
                return Ok(ModuleLock { _file: file });
            }
            let error = std::io::Error::last_os_error();
            if error.kind() != std::io::ErrorKind::Interrupted {
                return Err(error).context("Failed to lock SuSFS module update");
            }
        }
    }

    #[cfg(not(target_os = "android"))]
    {
        let guard = MODULE_MUTEX
            .lock()
            .map_err(|_| anyhow::anyhow!("SuSFS module lock is poisoned"))?;
        Ok(ModuleLock { _guard: guard })
    }
}

fn remove_path(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() => {
            fs::remove_dir_all(path).with_context(|| format!("Failed to remove {}", path.display()))
        }
        Ok(_) => {
            fs::remove_file(path).with_context(|| format!("Failed to remove {}", path.display()))
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("Failed to inspect {}", path.display())),
    }
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<()> {
    File::open(path)
        .and_then(|directory| directory.sync_all())
        .with_context(|| format!("Failed to sync directory {}", path.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn sync_directory(_: &Path) -> Result<()> {
    Ok(())
}

fn write_module_file(path: &Path, content: &str, mode: u32) -> Result<()> {
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    options.mode(mode);
    #[cfg(not(unix))]
    let _ = mode;

    let mut file = options
        .open(path)
        .with_context(|| format!("Failed to create {}", path.display()))?;
    file.write_all(content.as_bytes())
        .with_context(|| format!("Failed to write {}", path.display()))?;
    file.sync_all()
        .with_context(|| format!("Failed to sync {}", path.display()))?;

    #[cfg(unix)]
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .with_context(|| format!("Failed to set permissions on {}", path.display()))?;
    Ok(())
}

fn recover_interrupted_update() -> Result<()> {
    let module = Path::new(MODULE_PATH);
    let backup = Path::new(MODULE_BACKUP_PATH);
    let stage = Path::new(MODULE_STAGE_PATH);

    if backup.exists() {
        if module.exists() {
            remove_path(backup)?;
        } else {
            fs::rename(backup, module).context("Failed to restore previous SuSFS module")?;
        }
    }
    remove_path(stage)
}

fn build_staged_module(config: &ModuleConfig, stage: &Path) -> Result<()> {
    fs::create_dir(stage).context("Failed to create staged SuSFS module")?;
    write_module_file(&stage.join("module.prop"), &module_prop(), 0o644)?;

    let scripts = [
        ("service.sh", generate_service_script(config)),
        ("post-fs-data.sh", generate_post_fs_data_script(config)),
        ("post-mount.sh", generate_post_mount_script()),
        ("boot-completed.sh", generate_boot_completed_script(config)),
    ];
    for (name, content) in scripts {
        write_module_file(&stage.join(name), &content, 0o755)?;
    }
    sync_directory(stage)
}

pub fn install_module() -> Result<()> {
    let config = crate::susfs_config::load_module_config()?;
    install_module_with_config(&config)
}

fn install_module_with_config(config: &ModuleConfig) -> Result<()> {
    let _lock = acquire_module_lock()?;
    fs::create_dir_all(MODULES_DIR).context("Failed to create modules directory")?;
    recover_interrupted_update()?;

    let module = Path::new(MODULE_PATH);
    let stage = Path::new(MODULE_STAGE_PATH);
    let backup = Path::new(MODULE_BACKUP_PATH);

    if let Err(error) = build_staged_module(config, stage) {
        let _ = remove_path(stage);
        return Err(error);
    }

    let had_previous = module.exists();
    if had_previous {
        fs::rename(module, backup).context("Failed to preserve previous SuSFS module")?;
    }

    if let Err(error) = fs::rename(stage, module) {
        if had_previous {
            let _ = fs::rename(backup, module);
        }
        let _ = remove_path(stage);
        return Err(error).context("Failed to activate staged SuSFS module");
    }

    sync_directory(Path::new(MODULES_DIR))?;
    if had_previous {
        remove_path(backup)?;
        sync_directory(Path::new(MODULES_DIR))?;
    }
    Ok(())
}

pub fn remove_module() -> Result<()> {
    let _lock = acquire_module_lock()?;
    remove_path(Path::new(MODULE_PATH))?;
    remove_path(Path::new(MODULE_STAGE_PATH))?;
    remove_path(Path::new(MODULE_BACKUP_PATH))?;
    if Path::new(MODULES_DIR).is_dir() {
        sync_directory(Path::new(MODULES_DIR))?;
    }
    Ok(())
}

pub fn is_module_installed() -> bool {
    [MODULE_PATH, MODULE_BACKUP_PATH]
        .iter()
        .map(PathBuf::from)
        .any(|path| path.join("module.prop").is_file())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> ModuleConfig {
        ModuleConfig {
            uname_value: DEFAULT_UNAME.to_owned(),
            build_time_value: DEFAULT_BUILD_TIME.to_owned(),
            execute_in_post_fs_data: false,
            sus_paths: vec!["/sdcard/Android/data/example".to_owned()],
            sus_loop_paths: vec!["/data/loop".to_owned()],
            sus_maps: vec!["/data/map".to_owned()],
            enable_log: false,
            kstat_configs: Vec::new(),
            add_kstat_paths: Vec::new(),
            hide_sus_mounts_for_all_procs: false,
            enable_hide_bl: false,
            enable_cleanup_residue: false,
            enable_avc_log_spoofing: false,
        }
    }

    #[test]
    fn service_wait_is_bounded_and_has_no_fixed_delay() {
        let script = generate_service_script(&test_config());
        assert!(script.contains("wait_for_path /sdcard/Android 90"));
        assert!(!script.contains("until [ -d"));
        assert!(!script.contains("sleep 45"));
    }

    #[test]
    fn generated_commands_quote_user_paths() {
        let mut config = test_config();
        config.sus_paths = vec!["/data/a path/it's".to_owned()];
        let script = generate_boot_completed_script(&config);
        assert!(script.contains("'/data/a path/it'\\''s'"));
    }

    #[test]
    fn module_metadata_uses_makosu_identity() {
        let metadata = module_prop();
        assert!(metadata.contains("name=MakoSU SuSFS"));
        assert!(metadata.contains("author=MakoSU"));
    }
}
